/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.oop.problems.string.calculator;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.InputStream;

class AppTest {

  @Test
  @DisplayName("main 테스트")
  void main() {
    String[] args = null;
    String input = "32435456436754325674356756762221212798 - 342283024803781287013 * 235465789800876543223456543454 + 12341251246 - 3453476564534 + 13476857565743 * 1234567";
    InputStream in = new ByteArrayInputStream(input.getBytes());
    System.setIn(in);
    App.main(args);
  }

}
